[tool.poetry]
name = "famuly_album"
version = "0.0.1"
description = ""
authors = ["Oleksander Shevchenko <oleksander.shevchenko777@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pillow = "^9.4.0"
opencv-python = "^4.7.0.68"
pyqt5 = "^5.15.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
