# Form implementation generated from reading ui file 'D:\Shevchenko\PetProjects\family_album\src\family_album\gui\py_ui\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FamilyAlbumUI(object):
    def setupUi(self, FamilyAlbumUI):
        FamilyAlbumUI.setObjectName("FamilyAlbumUI")
        FamilyAlbumUI.resize(1062, 621)
        self.centralwidget = QtWidgets.QWidget(parent=FamilyAlbumUI)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setLineWidth(2)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.directories_space = QtWidgets.QFrame(parent=self.splitter)
        self.directories_space.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.directories_space.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.directories_space.setObjectName("directories_space")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.files_space = QtWidgets.QFrame(parent=self.tab)
        self.files_space.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.files_space.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.files_space.setObjectName("files_space")
        self.verticalLayout_2.addWidget(self.files_space)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.organazing_space = QtWidgets.QFrame(parent=self.tab_2)
        self.organazing_space.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.organazing_space.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.organazing_space.setObjectName("organazing_space")
        self.verticalLayout.addWidget(self.organazing_space)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.splitter)
        FamilyAlbumUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=FamilyAlbumUI)
        self.statusbar.setObjectName("statusbar")
        FamilyAlbumUI.setStatusBar(self.statusbar)

        self.retranslateUi(FamilyAlbumUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FamilyAlbumUI)

    def retranslateUi(self, FamilyAlbumUI):
        _translate = QtCore.QCoreApplication.translate
        FamilyAlbumUI.setWindowTitle(_translate("FamilyAlbumUI", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FamilyAlbumUI", "Duplication check"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("FamilyAlbumUI", "Organize structure"))
