# Form implementation generated from reading ui file 'D:\Shevchenko\PetProjects\family_album\src\family_album\gui\widgets\py_ui\file_organizer_ui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(614, 461)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_folder_selected = QtWidgets.QLabel(parent=Form)
        self.lbl_folder_selected.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_folder_selected.setObjectName("lbl_folder_selected")
        self.verticalLayout.addWidget(self.lbl_folder_selected)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_analyze = QtWidgets.QPushButton(parent=Form)
        self.pb_analyze.setObjectName("pb_analyze")
        self.horizontalLayout.addWidget(self.pb_analyze)
        self.pb_organize = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_organize.sizePolicy().hasHeightForWidth())
        self.pb_organize.setSizePolicy(sizePolicy)
        self.pb_organize.setMinimumSize(QtCore.QSize(0, 0))
        self.pb_organize.setMaximumSize(QtCore.QSize(300, 30))
        self.pb_organize.setObjectName("pb_organize")
        self.horizontalLayout.addWidget(self.pb_organize)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_info = QtWidgets.QLabel(parent=Form)
        self.lbl_info.setObjectName("lbl_info")
        self.gridLayout.addWidget(self.lbl_info, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.tbl_file_data = QtWidgets.QTableView(parent=Form)
        self.tbl_file_data.setObjectName("tbl_file_data")
        self.gridLayout.addWidget(self.tbl_file_data, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_folder_selected.setText(_translate("Form", "<>"))
        self.pb_analyze.setToolTip(_translate("Form", "Calculate how many files and subfolders are in selected folder"))
        self.pb_analyze.setText(_translate("Form", "Analyze"))
        self.pb_organize.setToolTip(_translate("Form", "Search for duplicate files by comparing file\'s hash between all files in selected folder and its subfolders"))
        self.pb_organize.setText(_translate("Form", "Organize files..."))
        self.lbl_info.setText(_translate("Form", "<>"))
